# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjDIL-o-17D7t901HB1agxS5aZhBdGCG
"""

!pip install datasets tensorflow opencv-python
from datasets import load_dataset

# Load dataset from Hugging Face Hub
ds = load_dataset("mohanwithdata/Medical_Plants_image")

# Save dataset locally
ds.save_to_disk("medical_plants_dataset")

# Install required libraries (only needed in Colab)

# Import required libraries
from datasets import load_from_disk
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image as keras_image
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from PIL import Image
from google.colab import files
from IPython.display import display, HTML

# ✅ Step 1: Load Dataset
ds = load_from_disk("medical_plants_dataset")

# ✅ Step 2: Preprocess Images
def preprocess_image(img, target_size=(299, 299)):
    img = tf.image.resize(img, target_size) / 255.0  # Resize & Normalize
    return img

def preprocess_dataset(dataset):
    images, labels = [], []
    for data in dataset:
        images.append(preprocess_image(data['image']))
        labels.append(data['label'])  # Ensure labels are extracted correctly
    return np.array(images), np.array(labels)

# Preprocess training & validation datasets
train_images, train_labels = preprocess_dataset(ds['train'])
val_images, val_labels = preprocess_dataset(ds['validation'])

# ✅ Step 3: Create TensorFlow Datasets for Efficient Training
train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels)).shuffle(1000).batch(32).prefetch(tf.data.experimental.AUTOTUNE)
val_dataset = tf.data.Dataset.from_tensor_slices((val_images, val_labels)).batch(32).prefetch(tf.data.experimental.AUTOTUNE)

# ✅ Step 4: Load Pre-Trained InceptionV3 Model
num_classes = len(ds['train'].features['label'].names)

base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(299, 299, 3))
base_model.trainable = False  # Freeze base model

# ✅ Step 5: Add Custom Layers
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation='softmax')
])

# ✅ Step 6: Compile & Train Model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(train_dataset, epochs=10, validation_data=val_dataset)

# ✅ Step 7: Evaluate Model
val_loss, val_acc = model.evaluate(val_dataset)
print(f'Validation Accuracy: {val_acc:.2f}')

# ✅ Step 8: Prediction Function with Medical Uses
def predict_plant(image_path):
    plant_names = ds['train'].features['label'].names

    # Medical uses dictionary
    plant_medical_uses = {
       "Alpinia Galanga (Rasna)": {
    "description": "Alpinia Galanga, also known as Rasna, is an important herb in Ayurvedic medicine, commonly used for its anti-inflammatory and analgesic properties. It is effective in treating joint pain, arthritis, and muscular disorders. The rhizomes contain essential oils, flavonoids, and other compounds that help reduce swelling, relieve pain, and improve circulation. Rasna also aids in digestion by stimulating digestive enzymes and is commonly used to treat gastrointestinal problems.",
    "applications": [
        "Used in Ayurvedic oils and decoctions for treating arthritis and joint pain.",
        "Effective in treating respiratory problems like asthma and bronchitis.",
        "Applied externally to treat wounds and infections.",
        "Boosts immune function and helps detoxify the body.",
        "Used in digestive tonics to relieve bloating and acidity."
    ]
},
"Amaranthus Viridis (Arive-Dantu)": {
    "description": "Amaranthus Viridis, or Arive-Dantu, is a nutrient-dense leafy vegetable with significant medicinal properties. It is particularly known for its ability to treat anemia due to its high iron content. This plant is also used to regulate digestion and alleviate constipation. Additionally, Arive-Dantu has diuretic properties, helping flush out toxins and prevent urinary tract infections.",
    "applications": [
        "Consumed to boost hemoglobin levels and treat anemia.",
        "Used to treat digestive disorders like diarrhea and bloating.",
        "Extracts are applied topically to promote faster wound healing.",
        "Supports kidney function and acts as a natural detoxifier.",
        "Helps reduce inflammation and improve skin health."
    ]
},
"Artocarpus Heterophyllus (Jackfruit)": {
    "description": "Jackfruit, known for its health benefits, is particularly effective in managing blood sugar levels and supporting heart health. The seeds and leaves are traditionally used to regulate blood sugar, which is beneficial for people with diabetes. The high fiber content in the fruit also promotes gut health, reduces constipation, and supports the digestive system.",
    "applications": [
        "Used in Ayurvedic medicine to control diabetes and improve metabolism.",
        "Jackfruit leaves are brewed into tea to regulate blood sugar.",
        "The fruit is consumed for its high fiber and antioxidant content.",
        "Applied externally as latex to heal wounds and infections.",
        "Supports heart health by lowering cholesterol and improving circulation."
    ]
},
"Azadirachta Indica (Neem)": {
    "description": "Neem is widely known for its antibacterial, antifungal, and antiviral properties. It is a common remedy for skin issues like acne, eczema, and psoriasis. Additionally, Neem is used for blood purification, liver detoxification, and managing diabetes by regulating blood sugar levels.",
    "applications": [
        "Neem leaves are used in skincare products to treat acne and other skin conditions.",
        "Neem oil is applied topically to wounds and skin infections.",
        "Used in oral care to prevent gum disease and bad breath.",
        "Neem extracts help in detoxification and boosting immunity.",
        "Acts as a natural pesticide and insect repellent."
    ]
},
"Basella Alba (Basale)": {
    "description": "Basella Alba, also known as Basale, is a leafy vegetable with a rich nutritional profile. It is particularly valued for its ability to treat anemia due to its high iron content. In addition to boosting hemoglobin levels, it is known for its digestive benefits and is used to treat constipation and indigestion.",
    "applications": [
        "Helps treat anemia by increasing iron levels in the body.",
        "Used to improve digestion and relieve constipation.",
        "Applied in skin treatments for its moisturizing and anti-inflammatory properties.",
        "Supports liver function and detoxification.",
        "Aids in reducing inflammation and promoting overall health."
    ]
},
"Brassica Juncea (Indian Mustard)": {
    "description": "Indian Mustard, or Brassica Juncea, is often used for its digestive and anti-inflammatory benefits. It helps in improving circulation and is traditionally used to treat respiratory conditions. The seeds of the plant contain essential oils that have been shown to improve joint health and treat conditions like arthritis.",
    "applications": [
        "Used to improve digestion and relieve bloating.",
        "Effective in treating respiratory conditions such as asthma.",
        "Used to alleviate joint pain and reduce inflammation.",
        "Mustard oil is applied topically for muscle and joint pain relief.",
        "Used to stimulate blood circulation and improve skin health."
    ]
},
"Carissa Carandas (Karanda)": {
    "description": "Carissa Carandas, commonly known as Karanda, is a fruit-bearing plant that has several medicinal uses. Its fruits are rich in vitamin C, making it useful for boosting immunity and preventing common colds. Additionally, Karanda is used to treat digestive disorders and has antioxidant properties that help in detoxification.",
    "applications": [
        "Used as a remedy for common colds and respiratory infections.",
        "Helps improve digestion and treat conditions like constipation.",
        "Used in skincare for its antioxidant and anti-aging properties.",
        "Helps detoxify the body and improve overall health.",
        "Consumed to strengthen the immune system and prevent infections."
    ]
},
"Citrus Limon (Lemon)": {
    "description": "Lemon, a widely used fruit, is known for its high vitamin C content, which supports the immune system. It also has powerful detoxifying properties and is used to cleanse the liver. Lemon is also used in skincare to brighten the skin and reduce acne.",
    "applications": [
        "Lemon juice is consumed to boost immunity and prevent colds.",
        "Used as a natural detoxifier to cleanse the liver and promote digestion.",
        "Applied topically to brighten the skin and reduce acne.",
        "Helps regulate blood pressure and improve heart health.",
        "Used as a natural remedy for sore throat and indigestion."
    ]
},
"Ficus Auriculata (Roxburgh fig)": {
    "description": "Ficus Auriculata, also known as the Roxburgh fig, has been traditionally used in treating a variety of health conditions. Its leaves and fruits are commonly used in treating respiratory issues and digestive disorders. The plant is also known for its anti-inflammatory properties.",
    "applications": [
        "Used to treat respiratory conditions like asthma and bronchitis.",
        "Helps in improving digestion and reducing bloating.",
        "Ficus leaf extracts are used for wound healing.",
        "Used to treat skin conditions such as eczema and acne.",
        "Helps reduce inflammation and promote overall health."
    ]
},
"Ficus Religiosa (Peepal Tree)": {
    "description": "Ficus Religiosa, also known as the Peepal Tree, is a sacred tree in many cultures and is widely used for its medicinal properties. The tree has been used to treat various ailments, including digestive disorders, respiratory issues, and skin problems.",
    "applications": [
        "Used to treat digestive disorders like constipation and indigestion.",
        "Peepal tree leaves are used in respiratory treatments to alleviate asthma.",
        "Applied topically for treating skin infections and wounds.",
        "Helps in boosting immunity and detoxifying the body.",
        "Used in traditional medicine to treat inflammation and joint pain."
    ]
},
    "Hibiscus Rosa-sinensis": {
    "description": "Hibiscus Rosa-sinensis, commonly known as Hibiscus, is renowned for its ability to improve heart health and reduce high blood pressure. Its flowers are rich in antioxidants, which help in fighting free radicals and promoting healthy skin. Additionally, hibiscus is used to treat digestive issues and promote liver health.",
    "applications": [
        "Used to lower blood pressure and improve heart health.",
        "Hibiscus tea is consumed to improve liver function and detoxify the body.",
        "Rich in antioxidants, it helps in preventing signs of aging and promoting healthy skin.",
        "Used to treat digestive disorders like constipation and bloating.",
        "Helps reduce inflammation and promote overall health."
    ]
},
"Jasminum (Jasmine)": {
    "description": "Jasminum, or Jasmine, is known for its calming and therapeutic effects. It is commonly used in aromatherapy to relieve stress, anxiety, and depression. The plant also has properties that can help with skin conditions and improve digestion.",
    "applications": [
        "Used in aromatherapy to reduce stress and anxiety.",
        "Jasmine oil is applied topically for skin conditions such as acne and eczema.",
        "Helps in improving digestion and relieving stomach discomfort.",
        "Used as a natural sedative to improve sleep quality.",
        "Acts as an anti-inflammatory agent and helps with joint pain."
    ]
},
"Mangifera Indica (Mango)": {
    "description": "Mango, the 'king of fruits,' is not only a delicious fruit but also a powerful medicinal plant. Mango is known for its rich vitamin C content, which boosts immunity and supports skin health. The leaves and seeds of the mango tree are also used in treating diabetes and improving digestive health.",
    "applications": [
        "Mango is consumed to boost immunity and prevent colds.",
        "The leaves are used to regulate blood sugar levels in diabetic patients.",
        "Mango extract is applied topically for its anti-aging properties.",
        "Helps improve digestive health and relieve constipation.",
        "Mango seeds are used in traditional medicine to treat diarrhea and stomach issues."
    ]
},
"Mentha (Mint)": {
    "description": "Mint, known for its cooling and soothing properties, is often used to treat digestive problems, including nausea, indigestion, and bloating. It also has antimicrobial properties and is used to treat skin conditions, such as acne and eczema. Mint is commonly used in teas and essential oils for its therapeutic effects.",
    "applications": [
        "Mint tea is used to soothe nausea, indigestion, and stomach discomfort.",
        "Mint oil is applied topically to treat headaches and migraines.",
        "Used in skincare for its cooling effect and to treat acne.",
        "Helps in improving breathing and treating respiratory conditions like asthma.",
        "Mint is used as a natural mouthwash to freshen breath and improve oral health."
    ]
},
"Moringa Oleifera (Drumstick)": {
    "description": "Moringa Oleifera, commonly known as Drumstick, is highly valued for its rich nutritional profile and medicinal benefits. It is rich in vitamins, minerals, and antioxidants, which help in reducing inflammation and promoting heart health. Moringa is also used in treating diabetes, improving digestion, and boosting immunity.",
    "applications": [
        "Used to treat diabetes by regulating blood sugar levels.",
        "Moringa powder is consumed to boost immunity and prevent infections.",
        "Helps reduce inflammation and is used in the treatment of arthritis.",
        "Moringa leaves are used to improve digestion and relieve constipation.",
        "Moringa oil is applied topically for its anti-aging and moisturizing properties."
    ]
},
"Muntingia Calabura (Jamaica Cherry-Gasagase)": {
    "description": "Muntingia Calabura, or Jamaica Cherry, is a small tropical tree known for its sweet-tasting fruit and its medicinal benefits. The fruit is rich in antioxidants, which help in detoxifying the body and improving skin health. The leaves of the tree are used for their anti-inflammatory and diuretic properties.",
    "applications": [
        "Used to improve skin health due to its high antioxidant content.",
        "Helps in detoxifying the body and improving overall health.",
        "The leaves are used as a diuretic to reduce fluid retention.",
        "Used in traditional medicine to reduce fever and treat infections.",
        "Helps improve digestion and alleviate constipation."
    ]
},
"Murraya Koenigii (Curry)": {
    "description": "Murraya Koenigii, commonly known as Curry leaves, is a highly aromatic plant that is not only a staple in cooking but also holds medicinal value. Curry leaves are used to treat indigestion, improve liver function, and regulate blood sugar levels. The leaves are also beneficial for maintaining healthy hair and preventing premature graying.",
    "applications": [
        "Curry leaves are used to treat digestive disorders like indigestion and diarrhea.",
        "Used to regulate blood sugar levels in diabetic patients.",
        "Curry leaf oil is applied to improve hair health and prevent hair loss.",
        "Helps improve liver function and detoxify the body.",
        "Used to treat skin conditions such as acne and eczema."
    ]
},
"Nerium Oleander (Oleander)": {
    "description": "Nerium Oleander, or Oleander, is a highly toxic plant but is used in small quantities in traditional medicine for its potent therapeutic properties. It is known for its ability to treat heart conditions, including congestive heart failure, and has anti-inflammatory properties used to treat joint pain and arthritis.",
    "applications": [
        "Used in small doses to treat heart conditions like congestive heart failure.",
        "Oleander extract is used to treat inflammatory diseases like arthritis.",
        "Helps reduce swelling and relieve joint pain.",
        "Used in traditional medicine for its anti-cancer properties.",
        "Oleander is used topically in wound healing and skin infections."
    ]
},
"Nyctanthes Arbor-tristis (Parijata)": {
    "description": "Nyctanthes Arbor-tristis, or Parijata, is a flowering tree known for its medicinal uses. It is used to treat conditions like fever, headaches, and insomnia. The flowers and leaves of the tree have therapeutic properties that help in reducing inflammation, boosting immunity, and promoting overall health.",
    "applications": [
        "Used to treat fever and reduce body temperature.",
        "The flowers are used in traditional medicine to relieve headaches and migraines.",
        "Helps improve sleep quality and alleviate insomnia.",
        "Parijata leaves are used for their anti-inflammatory properties.",
        "Boosts immunity and helps in detoxifying the body."
    ]
},
"Ocimum Tenuiflorum (Tulsi)": {
    "description": "Ocimum Tenuiflorum, or Tulsi, is considered a sacred plant in India and is revered for its numerous medicinal properties. It is known for its ability to boost immunity, reduce stress, and support respiratory health. Tulsi leaves are used to treat common colds, headaches, and digestive issues.",
    "applications": [
        "Used to treat respiratory conditions like asthma and bronchitis.",
        "Tulsi is consumed to boost immunity and fight off infections.",
        "Used to reduce stress and anxiety through its adaptogenic properties.",
        "Tulsi tea is used to relieve digestive issues and improve gut health.",
        "Applied topically to treat skin conditions and promote healing."
    ]
},
"Piper Betle (Betel)": {
    "description": "Piper Betle, or Betel, is commonly chewed as a stimulant and is known for its antimicrobial properties. It is used in traditional medicine to treat digestive issues, such as indigestion and ulcers. Betel leaves are also used for their anti-inflammatory and analgesic effects.",
    "applications": [
        "Betel leaves are chewed to aid digestion and relieve stomach discomfort.",
        "Used in the treatment of ulcers and gastrointestinal issues.",
        "Betel leaves are used to treat respiratory problems like cough and asthma.",
        "Helps reduce inflammation and relieve pain.",
        "Used as a natural remedy for oral health problems and bad breath."
    ]
},
      "Plectranthus Amboinicus (Mexican Mint)": {
    "description": "Plectranthus Amboinicus, also known as Mexican Mint or Cuban Oregano, is a perennial herb that is commonly used in traditional medicine for its antifungal, antimicrobial, and anti-inflammatory properties. The leaves of this plant are used to treat respiratory infections, digestive issues, and to relieve pain.",
    "applications": [
        "Used to treat respiratory infections like cough, cold, and bronchitis.",
        "The leaves are applied topically for pain relief and to reduce inflammation.",
        "Used in the treatment of indigestion and stomach discomfort.",
        "Mexican Mint is known to boost immunity and fight off infections.",
        "The plant is also used in the treatment of fungal infections and wounds."
    ]
},
"Pongamia Pinnata (Indian Beech)": {
    "description": "Pongamia Pinnata, commonly known as Indian Beech or Karanja, is a tree with medicinal properties used in traditional Ayurvedic medicine. The plant is known for its ability to treat skin diseases, infections, and promote overall health. The oil extracted from its seeds is used to treat various ailments such as arthritis, diabetes, and even malaria.",
    "applications": [
        "The oil is used to treat skin conditions like eczema, psoriasis, and fungal infections.",
        "Used to treat diabetes by regulating blood sugar levels.",
        "The leaves and seeds are used to treat fever and malaria.",
        "Pongamia oil is applied to alleviate joint pain and inflammation in arthritis.",
        "Used in traditional medicine to improve liver function and detoxify the body."
    ]
},
"Psidium Guajava (Guava)": {
    "description": "Psidium Guajava, commonly known as Guava, is a tropical fruit that is packed with vitamins and antioxidants, making it a powerhouse for boosting immunity and improving overall health. Guava leaves have medicinal properties that help in treating diarrhea, reducing blood sugar levels, and promoting digestive health.",
    "applications": [
        "Guava leaves are used to treat diarrhea and gastrointestinal disorders.",
        "The fruit is rich in vitamin C and is consumed to boost immunity and prevent colds.",
        "Used to regulate blood sugar levels in diabetic patients.",
        "Guava leaf extract is applied topically to treat wounds and skin infections.",
        "Consuming guava helps improve digestion and relieve constipation."
    ]
},
"Punica Granatum (Pomegranate)": {
    "description": "Punica Granatum, or Pomegranate, is a fruit that is highly prized for its antioxidant-rich properties. It is widely used to improve heart health, reduce cholesterol, and fight inflammation. Pomegranate has a number of medicinal uses, including its ability to treat digestive issues, enhance skin health, and prevent cancer.",
    "applications": [
        "Used to improve heart health by lowering cholesterol and blood pressure.",
        "Pomegranate juice is consumed to boost immunity and fight infections.",
        "Known for its anti-inflammatory properties, it helps reduce joint pain and arthritis.",
        "Pomegranate is used to treat digestive problems like indigestion and constipation.",
        "Its seeds are used topically for skin health and to reduce signs of aging."
    ]
},
"Santalum Album (Sandalwood)": {
    "description": "Santalum Album, or Sandalwood, is a fragrant wood known for its calming and therapeutic effects. Sandalwood oil is used in aromatherapy to reduce stress, anxiety, and promote mental clarity. Additionally, Sandalwood is used in skin care for its anti-aging, anti-inflammatory, and antiseptic properties.",
    "applications": [
        "Sandalwood oil is used in aromatherapy to relieve stress and promote relaxation.",
        "Applied topically to treat acne, reduce scars, and improve skin tone.",
        "Used as a natural remedy for headaches and to improve mental clarity.",
        "Sandalwood is known for its anti-inflammatory properties and is used to reduce joint pain.",
        "Helps in treating urinary tract infections and promoting overall kidney health."
    ]
},
"Syzygium Cumini (Jamun)": {
    "description": "Syzygium Cumini, or Jamun, is a tropical fruit with numerous medicinal uses, especially for regulating blood sugar levels. It is often used in traditional medicine to treat diabetes, digestive issues, and to enhance overall health. Jamun also has antimicrobial and antioxidant properties.",
    "applications": [
        "Used to regulate blood sugar levels and manage diabetes.",
        "Jamun fruit and seeds are used to treat digestive issues like diarrhea and constipation.",
        "Jamun juice is consumed to boost immunity and improve liver function.",
        "Its antioxidant properties help in fighting free radicals and promoting healthy skin.",
        "The fruit is used in traditional medicine to treat urinary tract infections."
    ]
},
"Syzygium Jambos (Rose Apple)": {
    "description": "Syzygium Jambos, commonly known as Rose Apple, is a tropical fruit that offers a range of medicinal benefits. The fruit is rich in antioxidants and vitamins, and is used to promote digestive health, treat skin conditions, and support heart health. The leaves and bark of the tree are also used for their antibacterial and anti-inflammatory properties.",
    "applications": [
        "Rose Apple fruit is consumed to improve digestion and treat digestive disorders.",
        "Used to treat skin conditions such as acne and eczema due to its antimicrobial properties.",
        "The leaves are used in traditional medicine to treat fever and reduce inflammation.",
        "Rose Apple is used to promote heart health by reducing blood pressure.",
        "The plant is also used in the treatment of respiratory conditions like asthma and cough."
    ]
},
"Tabernaemontana Divaricata (Crape Jasmine)": {
    "description": "Tabernaemontana Divaricata, commonly known as Crape Jasmine, is a flowering shrub known for its medicinal uses in treating a variety of ailments. The plant is commonly used in Ayurvedic medicine to treat fever, anxiety, and sleep disorders. The flowers, leaves, and roots have therapeutic properties for promoting overall health.",
    "applications": [
        "Used to treat fever and reduce body temperature.",
        "The leaves are used in traditional medicine to relieve headaches and improve sleep.",
        "Crape Jasmine is used to reduce anxiety and stress.",
        "Helps in treating respiratory problems like cough and asthma.",
        "The plant is also used to improve skin health and treat wounds."
    ]
},
"Trigonella Foenum-graecum (Fenugreek)": {
    "description": "Trigonella Foenum-graecum, or Fenugreek, is an herb widely used in both cooking and traditional medicine. It is known for its ability to regulate blood sugar levels, improve digestive health, and boost lactation in nursing mothers. Fenugreek also has anti-inflammatory and antioxidant properties.",
    "applications": [
        "Used to regulate blood sugar levels and treat diabetes.",
        "Fenugreek is consumed to boost lactation in nursing mothers.",
        "Helps improve digestion and relieve constipation.",
        "Used in skincare for its anti-aging properties and to treat acne.",
        "Fenugreek seeds are used to reduce inflammation and treat joint pain."
    ]
    }
  }

    # Load and preprocess image
    img = keras_image.load_img(image_path, target_size=(299, 299))
    img_array = keras_image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict class
    predictions = model.predict(img_array)
    predicted_class = np.argmax(predictions, axis=1)[0]
    predicted_plant_name = plant_names[predicted_class]

    # Get medical use
    medical_use = plant_medical_uses.get(predicted_plant_name, "No medical use found.")
    return predicted_plant_name, medical_use

# ✅ Step 9: Save Model in Recommended Format
model.save('medical_use_model.keras')

# ✅ Step 10: Upload & Predict on a New Image

uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Display the image
img = Image.open(image_path)
plt.imshow(img)
plt.axis('off')
plt.show()

from IPython.core.display import display, HTML
import base64

def encode_image(image_path):
    with open(image_path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode("utf-8")
plant_name, medical_info = predict_plant(image_path)

# Extract description and applications
description = medical_info["description"]
applications = "".join([f"<li>{app}</li>" for app in medical_info["applications"]])

# Convert the image path to display it in HTML
image_path_url = f"data:image/jpeg;base64,{encode_image(image_path)}"

# Styling and formatting the output
display(HTML(f"""
    <div style='
        font-family: "Poppins", Arial, sans-serif;
        padding: 25px;
        background: linear-gradient(to right, #d4fc79, #96e6a1);
        border-radius: 15px;
        text-align: center;
        max-width: 750px;
        margin: auto;
        box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.2);'>

        <!-- Plant Image -->
        <img src='{image_path_url}' alt='Plant Image' style='
            width: 100%;
            max-height: 350px;
            object-fit: cover;
            border-radius: 10px;
            box-shadow: 0px 4px 8px rgba(0,0,0,0.2);
            margin-bottom: 20px;'>

        <h1 style='
            color: #2c3e50;
            font-size: 38px;
            font-weight: bold;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.2);'>🌿 {plant_name}</h1>

        <p style='
            font-size: 22px;
            color: #34495e;
            line-height: 1.7;
            font-weight: 500;
            padding: 10px;
            background: rgba(255, 255, 255, 0.4);
            border-radius: 10px;'>
            {description}
        </p>

        <h2 style='
            color: #16a085;
            font-size: 28px;
            margin-top: 20px;
            text-transform: uppercase;
            letter-spacing: 1px;'>Applications</h2>

        <ul style='
            font-size: 20px;
            color: #34495e;
            text-align: left;
            padding-left: 40px;
            max-width: 600px;
            margin: auto;
            list-style-type: "🌱";'>
            {applications}
        </ul>
    </div>
"""))


# Save
model.save("medical_plant_model.keras")

# Load
from keras.models import load_model
model = load_model("medical_plant_model.keras")